excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://aayush251.github.io/
title: Aayush Sharma
tagline: A Little place to hide.
description: I am kind of a developer, designer and gamer,
paginate: 5
highlighter: rouge